version: "3.2"

services:

  builder:
    build:
      dockerfile: ./docker/Dockerfile.frontend.yml
    volumes:
#      - ./monopoly/frontend:/home/app
      - ./dnd/frontend:/home/app
    networks:
      - dockerNet

  front-dev:
    build:
      dockerfile: ./docker/Dockerfile.frontend.yml
    volumes:
      - ./dnd/frontend:/home/app
    ports:
      - 3000:3000
    command: bash -c "yarn run dev"

  front:
    build:
      dockerfile: ./docker/Dockerfile.frontend.yml
    volumes:
#      - ./monopoly/frontend:/home/app
      - ./docker/nginx/nginx.conf:/home/app
    ports:
      - 3000:3000
    networks:
      - dockerNet
    command: bash -c "yarn run prod"

  nginx:
    image: nginx:latest
    networks:
      - dockerNet
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  dockerNet: