version: "3.2"

services:

  builder:
    build:
      dockerfile: ./docker/Dockerfile.frontend.yml
    volumes:
      - ./frontend:/home/app
    networks:
      - dockerNet

  front:
    build:
      dockerfile: ./docker/Dockerfile.frontend.yml
#    stdin_open: true
#    tty: true
    volumes:
      - ./frontend:/home/app
      - ./docker/nginx/nginx.conf:/home/app
    ports:
      - 3000:3000
#    deploy:
#      resources:
#        limits:
#          memory: 2GB
#          cpus: '0.5'
    networks:
      - dockerNet

  nginx:
    image: nginx:latest
    networks:
      - dockerNet
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  dockerNet: