version: "3.2"

services:

  builder:
    build:
      dockerfile: docker/Dockerfile.frontend.yml
    image: frontend
    volumes:
      - game-helper-volume:/home/app
      - .:/home/repo

  front:
    build:
      dockerfile: docker/Dockerfile.frontend.yml
    image: frontend
    stdin_open: true
    tty: true
    volumes:
      - game-helper-volume:/home/app
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: '0.5'

volumes:
  game-helper-volume:
