FROM --platform=linux/amd64 node:20 as node

WORKDIR /home/app

RUN apt-get update -y && apt-get install -y curl nano zsh
RUN npm install -g npm@8.12.1
RUN npm install -g pnpm

CMD ["yarn", "run", "prod"]