FROM node:20 as node

rm -rf ./node_modules 
rm -f ./package-lock.json
rm -f ./yarn-error.log

COPY . /home/app

WORKDIR /home/app

RUN apt-get update -y && apt-get install -y curl nano zsh
RUN npm install -g npm@8.12.1
RUN npm install -g pnpm

