const schemes = [
    {
        id: 'classic',
        name: 'Classic',
    },
    {
        id: 'russian-cities-v2',
        name: 'Russian Cities v2',
        startBalance: 1500,
        operations: [
            {
                id: 'buy',
                name: 'Купить город'
            },
            {
                id: 'upgrade',
                name: 'Upgrade города'
            },
            {
                id: 'outcome',
                name: 'Оплаты'
            },
            {
                id: 'income',
                name: 'Выплаты'
            },
        ],
        fieldTypes: [
            'city', 'railroad', 'infra', 'prison', 'start', 'chance', 'bank', 'tax', 'parking',
        ],
        fields: [
            {type: 'start'},
            {type: 'city', id: 'Тюмень'},
            {type: 'bank',},
            {type: 'city', id: 'Самара'},
            {type: 'tax', amount: -200},
            {type: 'railroad', id: 'Рижская железная дорога'},
            {type: 'city', id: 'Калуга'},
            {type: 'chance'},
            {type: 'city', id: 'Пермь'},
            {type: 'city', id: 'Томск'},
            {type: 'prison', amount: -50},
            {type: 'city', id: 'Уфа'},
            {type: 'infra', id: 'Электростанция'},
            {type: 'city', id: 'Казань'},
            {type: 'city', id: 'Краснодар'},
            {type: 'railroad', id: 'Курская железная дорога'},
            {type: 'city', id: 'Архангельск'},
            {type: 'bank',},
            {type: 'city', id: 'Челябинск'},
            {type: 'city', id: 'Нижний Новгород'},
            {type: 'parking'},
            {type: 'city', id: 'Омск'},
            {type: 'chance'},
            {type: 'city', id: 'Волгоград'},
            {type: 'city', id: 'Белгород'},
            {type: 'railroad', id: 'Казанская железная дорога'},
            {type: 'city', id: 'Ставрополь'},
            {type: 'city', id: 'Ростов-на-Дону'},
            {type: 'infra', id: 'Водопровод'},
            {type: 'city', id: 'Хабаровск'},
            {type: 'prison', amount: -50},
            {type: 'city', id: 'Екатеринбург'},
            {type: 'city', id: 'Владивосток'},
            {type: 'bank',},
            {type: 'city', id: 'Санкт-Пертербург'},
            {type: 'railroad', id: 'Ленинградская железная дорога'},
            {type: 'chance'},
            {type: 'city', id: 'Москва'},
            {type: 'tax', amount: -100},
            {type: 'city', id: 'Новосибирск'},
        ],
        currencyTypes: [
            5, 10, 50, 100, 500, 1000, 5000
        ],
        roundIncomeAmount: 200,
        properties: [
            {id:'Архангельск', groupColor: 'orange', type: 'city',
                upgrades: [
                    {price:180, tax: 14, level: 0},
                    {price:100, tax: 70, level: 1},
                    {price:100, tax: 200, level: 2},
                    {price:100, tax: 550, level: 3},
                    {price:100, tax: 750, level: 4},
                    {price:100, tax: 950, level: 5},
                ]},
            {id:'Белгород', groupColor: 'red', type: 'city',
                upgrades: [
                    {price:240, tax: 18, level: 0},
                    {price:150, tax: 90, level: 1},
                    {price:150, tax: 250, level: 2},
                    {price:150, tax: 700, level: 3},
                    {price:150, tax: 875, level: 4},
                    {price:150, tax: 1050, level: 5},
                ]},
            {id:'Владивосток', groupColor: 'green', type: 'city',
                upgrades: [
                    {price:300, tax: 26, level: 0},
                    {price:200, tax: 130, level: 1},
                    {price:200, tax: 390, level: 2},
                    {price:200, tax: 900, level: 3},
                    {price:200, tax: 1100, level: 4},
                    {price:200, tax: 1275, level: 5},
                ]},
            {id:'Водопровод', type: 'infra', upgrades: [
                {price:150, tax: 0, level: 1}
                ]},
            {id:'Волгоград', groupColor: 'red', type: 'city',
                upgrades: [
                    {price:220, tax: 18, level: 0},
                    {price:150, tax: 90, level: 1},
                    {price:150, tax: 250, level: 2},
                    {price:150, tax: 700, level: 3},
                    {price:150, tax: 875, level: 4},
                    {price:150, tax: 1050, level: 5},
                ]},
            {id:'Екатеринбург', groupColor: 'green', type: 'city',
                upgrades: [
                    {price:300, tax: 26, level: 0},
                    {price:200, tax: 130, level: 1},
                    {price:200, tax: 390, level: 2},
                    {price:200, tax: 900, level: 3},
                    {price:200, tax: 1100, level: 4},
                    {price:200, tax: 1275, level: 5},
                ]},
            {id:'Казанская железная дорога', type:'railroad', upgrades: [
                {price:200, tax: 0, level: 1},
                ]},
            {id:'Казань', groupColor: 'pink', type: 'city',
                upgrades: [
                    {price:140, tax: 10, level: 0},
                    {price:100, tax: 50, level: 1},
                    {price:100, tax: 150, level: 2},
                    {price:100, tax: 450, level: 3},
                    {price:100, tax: 625, level: 4},
                    {price:100, tax: 750, level: 5},
                ]},
            {id:'Калуга', groupColor: 'light-blue', type: 'city',
                upgrades: [
                    {price:100, tax: 6, level: 0},
                    {price:50, tax: 30, level: 1},
                    {price:50, tax: 90, level: 2},
                    {price:50, tax: 270, level: 3},
                    {price:50, tax: 400, level: 4},
                    {price:50, tax: 550, level: 5},
                ]},
            {id:'Краснодар', groupColor: 'pink', type: 'city',
                upgrades: [
                    {price:160, tax: 12, level: 0},
                    {price:100, tax: 60, level: 1},
                    {price:100, tax: 180, level: 2},
                    {price:100, tax: 500, level: 3},
                    {price:100, tax: 700, level: 4},
                    {price:100, tax: 900, level: 5},
                ]},
            {id:'Курская железная дорога', type:'railroad', upgrades: [
                {price:200, tax: 0, level: 1},
                ]},
            {id:'Ленинградская железная дорога', type:'railroad', upgrades: [
                {price:200, tax: 0, level: 1},
                ]},
            {id:'Москва', groupColor: 'blue', type: 'city',
                upgrades: [
                    {price:350, tax: 35, level: 0},
                    {price:200, tax: 175, level: 1},
                    {price:200, tax: 500, level: 2},
                    {price:200, tax: 1100, level: 3},
                    {price:200, tax: 1300, level: 4},
                    {price:200, tax: 1500, level: 5},
                ]},
            {id:'Нижний Новгород', groupColor: 'orange', type: 'city',
                upgrades: [
                    {price:200, tax: 16, level: 0},
                    {price:100, tax: 80, level: 1},
                    {price:100, tax: 220, level: 2},
                    {price:100, tax: 600, level: 3},
                    {price:100, tax: 800, level: 4},
                    {price:100, tax: 1000, level: 5},
                ]},
            {id:'Новосибирск', groupColor: 'blue', type: 'city',
                upgrades: [
                    {price:400, tax: 50, level: 0},
                    {price:200, tax: 200, level: 1},
                    {price:200, tax: 600, level: 2},
                    {price:200, tax: 1400, level: 3},
                    {price:200, tax: 1700, level: 4},
                    {price:200, tax: 2000, level: 5},
                ]},
            {id:'Омск', groupColor: 'red', type: 'city',
                upgrades: [
                    {price:220, tax: 18, level: 0},
                    {price:150, tax: 90, level: 1},
                    {price:150, tax: 250, level: 2},
                    {price:150, tax: 700, level: 3},
                    {price:150, tax: 875, level: 4},
                    {price:150, tax: 1050, level: 5},
                ]},
            {id:'Пермь', groupColor: 'light-blue', type: 'city',
                upgrades: [
                    {price:100, tax: 6, level: 0},
                    {price:50, tax: 30, level: 1},
                    {price:50, tax: 90, level: 2},
                    {price:50, tax: 270, level: 3},
                    {price:50, tax: 400, level: 4},
                    {price:50, tax: 550, level: 5},
                ]},
            {id:'Рижская железная дорога', type:'railroad', upgrades: [
                    {price:200, tax: 0, level: 0},
                ]},
            {id:'Ростов-на-Дону', groupColor: 'yellow', type: 'city',
                upgrades: [
                    {price:260, tax: 22, level: 0},
                    {price:150, tax: 110, level: 1},
                    {price:150, tax: 330, level: 2},
                    {price:150, tax: 800, level: 3},
                    {price:150, tax: 975, level: 4},
                    {price:150, tax: 1150, level: 5},
                ]},
            {id:'Самара', groupColor: 'brown', type: 'city',
                upgrades: [
                    {price:60, tax: 4, level: 0},
                    {price:50, tax: 20, level: 1},
                    {price:50, tax: 60, level: 2},
                    {price:50, tax: 180, level: 3},
                    {price:50, tax: 320, level: 4},
                    {price:50, tax: 450, level: 5},
                ]},
            {id:'Санкт-Петербург', groupColor: 'green', type: 'city',
                upgrades: [
                    {price:320, tax: 28, level: 0},
                    {price:200, tax: 150, level: 1},
                    {price:200, tax: 450, level: 2},
                    {price:200, tax: 1000, level: 3},
                    {price:200, tax: 1200, level: 4},
                    {price:200, tax: 1400, level: 5},
                ]},
            {id:'Ставрополь', groupColor: 'yellow', type: 'city',
                upgrades: [
                    {price:260, tax: 22, level: 0},
                    {price:150, tax: 110, level: 1},
                    {price:150, tax: 330, level: 2},
                    {price:150, tax: 800, level: 3},
                    {price:150, tax: 975, level: 4},
                    {price:150, tax: 1150, level: 5},
                ]},
            {id:'Томск', groupColor: 'light-blue', type: 'city',
                upgrades: [
                    {price:120, tax: 8, level: 0},
                    {price:50, tax: 40, level: 1},
                    {price:50, tax: 100, level: 2},
                    {price:50, tax: 300, level: 3},
                    {price:50, tax: 450, level: 4},
                    {price:50, tax: 600, level: 5},
                ]},
            {id:'Тюмень', groupColor: 'brown', type: 'city',
                upgrades: [
                    {price:60, tax: 2, level: 0},
                    {price:50, tax: 10, level: 1},
                    {price:50, tax: 30, level: 2},
                    {price:50, tax: 90, level: 3},
                    {price:50, tax: 160, level: 4},
                    {price:50, tax: 250, level: 5},
                ]},
            {id:'Уфа', groupColor: 'pink', type: 'city',
                upgrades: [
                    {price:140, tax: 10, level: 0},
                    {price:100, tax: 50, level: 1},
                    {price:100, tax: 150, level: 2},
                    {price:100, tax: 450, level: 3},
                    {price:100, tax: 625, level: 4},
                    {price:100, tax: 750, level: 5},
                ]},
            {id:'Хабаровск', groupColor: 'yellow', type: 'city',
                upgrades: [
                    {price:280, tax: 24, level: 0},
                    {price:150, tax: 120, level: 1},
                    {price:150, tax: 360, level: 2},
                    {price:150, tax: 850, level: 3},
                    {price:150, tax: 1025, level: 4},
                    {price:150, tax: 1200, level: 5},
                ]},
            {id:'Челябинск', groupColor: 'orange', type: 'city',
                upgrades: [
                    {price:180, tax: 14, level: 0},
                    {price:100, tax: 70, level: 1},
                    {price:100, tax: 200, level: 2},
                    {price:100, tax: 550, level: 3},
                    {price:100, tax: 750, level: 4},
                    {price:100, tax: 950, level: 5},
                ]},
            {id:'Электростанция', type: 'infra', upgrades: [
                {price:150, tax: 0, level: 0},
                ]},
        ],
    }
];

export default schemes;